import Link from "next/link";

const readings = [
  {
    tier: "free",
    name: "Temperament Snapshot",
    price: "Free",
    tagline: "Know yourself in 60 seconds.",
    what: "Using Gadbury's 6-factor method, we analyze your rising sign, planetary ruler, Moon phase, Sun season, and planetary orientality to identify your dominant temperament, manners, and type of intelligence.",
    includes: [
      "Dominant temperament (Choleric, Sanguine, Phlegmatic, or Melancholic)",
      "Manners — how you come across to others",
      "Wit & intelligence — your type of mind",
      "Character synthesis paragraph",
    ],
    cta: "Get Free Snapshot",
    href: "/start",
  },
  {
    tier: "full",
    name: "Full Natal Reading",
    price: "$75",
    tagline: "The complete picture of your natal chart.",
    what: "A comprehensive reading covering every major life area in William Lilly's tradition. Career, income timing, relationships, marriage pattern, children, health constitution, and a key themes synthesis.",
    includes: [
      "Temperament, manners & intelligence (Skill 01)",
      "Income strength & Bonatti's life thirds timing (Skill 02)",
      "Career path & triple significator vocation method (Skill 02)",
      "Marriage pattern — number, quality, partner profile (Skill 03)",
      "Children & fertility assessment (Skill 03)",
      "Constitutional health & vulnerability areas (Skill 04)",
      "Key themes synthesis tying all areas together",
    ],
    cta: "Order Full Reading — $75",
    href: "/book?tier=full",
  },
  {
    tier: "timing",
    name: "Timing Subscription",
    price: "$27/month",
    tagline: "Know the season you're in — every month.",
    what: "The ancient Firdaria planetary period system shows which planet rules your current life chapter. Combined with your annual Solar Revolution, you'll understand what's activated now and how to work with it.",
    includes: [
      "Current Firdaria major period — your life chapter",
      "Current Firdaria minor period — this season within the chapter",
      "Solar Revolution for this year — key areas activated",
      "Firdaria + Solar Revolution synthesis",
      "Monthly update with practical guidance",
      "Access to all past readings in your dashboard",
    ],
    cta: "Subscribe — $27/month",
    href: "/book?tier=subscription",
  },
];

const faqs = [
  {
    q: "What information do I need to provide?",
    a: "Your full birth data: date of birth, time of birth (as exact as possible), and city/country of birth. If you don't know your birth time, we can still do a partial reading using a noon chart, but certain house-based factors will be approximate.",
  },
  {
    q: "How long does a full reading take to receive?",
    a: "Full natal readings are generated by AI and typically delivered within 5-10 minutes of completing your order. You'll receive an email with a link to your reading in your dashboard.",
  },
  {
    q: "What tradition does this use?",
    a: "All readings use the traditional Renaissance method: Regiomontanus house system, Ptolemaic aspects, the seven traditional planets, Dorothean triplicities, and essential dignities. This is the system of William Lilly (Christian Astrology, 1647) — the most complete traditional system in English.",
  },
  {
    q: "How is this different from modern astrology?",
    a: "Traditional astrology uses a rigorous dignity system that tells you whether a planet is strong or weak in a chart — which determines whether its influence is positive or negative. Modern astrology typically ignores this. Traditional readings are more precise and more specific as a result.",
  },
  {
    q: "Can I cancel my subscription?",
    a: "Yes, anytime. You'll continue to have access until the end of your billing period.",
  },
];

export default function ReadingsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16">
      <div className="text-center mb-16">
        <p className="text-gold-400 text-sm tracking-widest uppercase mb-3">Reading Options</p>
        <h1 className="text-4xl font-serif text-stone-50 mb-4">
          Choose Your Reading
        </h1>
        <p className="text-stone-400 max-w-xl mx-auto">
          All readings use William Lilly&apos;s traditional Renaissance method — the most precise
          natal astrology system developed in the Western tradition.
        </p>
      </div>

      <div className="space-y-10 mb-20">
        {readings.map((r) => (
          <div key={r.tier} className="card-dark">
            <div className="flex flex-col md:flex-row md:items-start gap-6">
              <div className="flex-1">
                <div className="flex items-baseline gap-3 mb-1">
                  <h2 className="text-2xl font-serif text-stone-50">{r.name}</h2>
                  <span className="text-gold-400 font-serif text-xl">{r.price}</span>
                </div>
                <p className="text-gold-300 text-sm italic mb-3">{r.tagline}</p>
                <p className="text-stone-400 text-sm leading-relaxed mb-5">{r.what}</p>
                <ul className="space-y-1.5">
                  {r.includes.map((item) => (
                    <li key={item} className="flex items-start gap-2 text-stone-300 text-sm">
                      <span className="text-gold-500 mt-0.5 shrink-0">✦</span>
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
              <div className="shrink-0">
                <Link href={r.href} className="btn-gold block text-center whitespace-nowrap">
                  {r.cta}
                </Link>
              </div>
            </div>
          </div>
        ))}
      </div>

      {/* FAQ */}
      <div className="border-t border-gold-900 pt-12">
        <h2 className="text-2xl font-serif text-gold-400 mb-8">Frequently Asked Questions</h2>
        <div className="space-y-6">
          {faqs.map((faq) => (
            <div key={faq.q}>
              <h3 className="text-stone-100 font-serif mb-2">{faq.q}</h3>
              <p className="text-stone-400 text-sm leading-relaxed">{faq.a}</p>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
