import Link from "next/link";

export default function AboutPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-16">
      <div className="text-center mb-12">
        <p className="text-gold-400 text-sm tracking-widest uppercase mb-3">About the Readings</p>
        <h1 className="text-4xl font-serif text-stone-50">
          The Renaissance Tradition
        </h1>
      </div>

      <div className="space-y-8 text-stone-300 leading-relaxed">
        <p>
          These readings are rooted in the European astrological tradition that flourished
          between 1200 and 1700 AD — a time when astrology was a rigorous learned discipline,
          practiced at royal courts and universities alike. The primary source is{" "}
          <em className="text-stone-200">Christian Astrology</em> (1647) by William Lilly, the
          most complete treatise on traditional natal astrology ever written in English.
        </p>

        <p>
          What distinguishes traditional astrology from its modern descendant is the{" "}
          <strong className="text-gold-300">essential dignity system</strong>. In traditional
          astrology, every planet is evaluated for strength or weakness based on its position
          relative to the zodiac. A planet in its own sign (domicile) or exaltation is strong
          — it can act effectively for the native. A planet in detriment or fall is weakened —
          it struggles to deliver. This single principle makes traditional readings dramatically
          more precise.
        </p>

        <div className="card-dark my-8">
          <h2 className="text-xl font-serif text-gold-400 mb-4">Why This Method Works</h2>
          <p className="text-stone-400 text-sm leading-relaxed">
            Modern astrology gives every planet equal weight. Traditional astrology asks:
            is this planet working for you or against you? The answer changes everything.
            Two people with Jupiter in their career house will have very different outcomes —
            one has Jupiter in Cancer (exalted, powerful) and one has Jupiter in Capricorn
            (fallen, weakened). The traditional method tells you which is which. Modern
            astrology cannot.
          </p>
        </div>

        <p>
          The readings use the{" "}
          <strong className="text-gold-300">Regiomontanus house system</strong>, which was the
          standard for serious traditional work. They employ the seven traditional planets
          (Sun, Moon, Mercury, Venus, Mars, Jupiter, Saturn), the Ptolemaic aspects, and the
          Dorothean triplicity system for calculating dignity.
        </p>

        <p>
          Timing is handled through{" "}
          <strong className="text-gold-300">Firdaria</strong>, the Persian planetary period
          system, and the <strong className="text-gold-300">Solar Revolution</strong> — the
          chart cast for the moment the Sun returns to its natal degree each year. These two
          methods work together to show which areas of life are activated for any given year
          or period.
        </p>

        <div className="section-divider" />

        <h2 className="text-2xl font-serif text-gold-400 mb-4">About This Service</h2>
        <p>
          These readings are generated by an AI trained on traditional astrological sources —
          Lilly, Gadbury, Bonatti, Schoener, and others. The AI follows the technical rules
          of the tradition precisely: identifying significators, assessing essential dignities,
          applying the hierarchical selection methods for manners and career, and synthesizing
          multiple indicators into a coherent reading.
        </p>

        <p>
          The goal is to make traditional Renaissance astrology accessible — readings that are
          technically accurate, personally meaningful, and practically useful.
        </p>

        <div className="card-dark">
          <p className="text-stone-400 text-sm">
            <strong className="text-gold-300">Disclaimer:</strong> These readings are provided
            for self-reflection and entertainment. They draw on a 400-year astrological
            tradition but should not be used as a substitute for professional financial, legal,
            medical, or psychological advice.
          </p>
        </div>
      </div>

      <div className="text-center mt-12">
        <Link href="/start" className="btn-gold inline-block">
          Get Your Free Temperament Snapshot
        </Link>
      </div>
    </div>
  );
}
